name: Build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: S3 Sync
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 cp ${{ secrets.S3_PATH }} ./database/test.sqlite
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Run test suite
      run: composer run-script test

    - name: Send Slack notification
      uses: 8398a7/action-slack@v2
      if: failure()
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
